# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
 default: &default
  adapter: postgresql
   encoding: unicode
   pool: 5
#   username: neondb_owner
#   password: npg_W6BDvTi4IVQC
#   host: ep-red-leaf-a8x55tje-pooler.eastus2.azure.neon.tech
#   port: 5432
#   database: rails_eunny_db
#   sslmode: require

# development:
#   <<: *default
#   database: rails_eunny_db


# test:
#   <<: *default
#   database: <%= ENV["DATABASE_NAME"] %>_test


  production:
  primary: &primary_production
    <<: *default
    database: rails_eunny_db
    username: piazza-web
    password: <%= ENV["PIAZZA_WEB_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_eunny_web_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_eunny_web_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_eunny_web_production_cable
    migrations_paths: db/cable_migrate
  